version: "3.0"
services:
  server:
    build: ./
    restart: on-failure
    volumes:
      - ./website-backend/receive-text:/usr/src/website-backend/receive-text
      - ./semantic-parser:/usr/src/semantic-parser
    environment:
      - NODE_ENV=development
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command: bash -c "cd /usr/src && ./receiver_parser_setup.sh"

  web:
    build: ./website-frontend
    restart: on-failure
    volumes:
      - ./website-frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command: bash -c "npm install && npm run devstart"

